const studentQuestions: Record<string, string[]> = {
  health: [
    "TOTAL SLEEP DURATION DURING THE PREVIOUS NIGHT?",
    "SELF-ASSESSED HYDRATION ADEQUACY?",
    "WAS MODERATE OR VIGOROUS PHYSICAL ACTIVITY COMPLETED?",
    "TOTAL STEP COUNT RECORDED TODAY?",
    "NUMBER OF NUTRITIONALLY COMPLETE MEALS CONSUMED?",
    "CURRENT ACADEMIC AND PERSONAL STRESS LOAD?",
    "WAS DEDICATED MOBILITY OR FLEXIBILITY WORK COMPLETED?",
    "MINUTES OF DIRECT OUTDOOR LIGHT EXPOSURE?",
    "CURRENT PHYSICAL ENERGY AVAILABILITY?",
    "WAS THE ESTABLISHED SLEEP SCHEDULE MAINTAINED?",
  ],
  studies: [
    "HOURS OF UNINTERRUPTED ACADEMIC STUDY COMPLETED?",
    "NUMBER OF NEW CONCEPTS RETAINED WITHOUT REFERENCE MATERIAL?",
    "FREQUENCY OF DEVICE OR ENVIRONMENTAL DISTRACTIONS?",
    "UNAIDED RECALL ACCURACY FOR TODAY'S MATERIAL?",
    "NUMBER OF PRACTICE QUESTIONS OR PROBLEMS COMPLETED?",
    "WAS SPACED-REPETITION REVIEW COMPLETED AS SCHEDULED?",
    "WERE RECOVERY BREAKS USED WITHOUT EXTENDING THEIR DURATION?",
    "PAGES PROCESSED WITH ACTIVE ANNOTATION OR NOTES?",
    "COGNITIVE ENERGY DURING THE FINAL STUDY BLOCK?",
    "IS THE NEXT STUDY BLOCK DEFINED BY SUBJECT AND START TIME?",
  ],
  future: [
    "MINUTES SPENT DEFINING POST-EDUCATION DIRECTION?",
    "MINUTES ALLOCATED TO A MARKETABLE SKILL OUTSIDE CORE COURSEWORK?",
    "WAS A MENTOR, PEER, OR PROFESSIONAL CONTACT ENGAGED?",
    "MEASURABLE PROGRESS TOWARD THE CURRENT DEVELOPMENT MILESTONE?",
    "MINUTES SPENT BUILDING A PORTFOLIO OR APPLICATION ASSET?",
    "WERE SCHOLARSHIP, INTERNSHIP, OR ENTRY-LEVEL OPPORTUNITIES REVIEWED?",
    "NUMBER OF PENDING EDUCATION OR CAREER DECISIONS RESOLVED?",
    "FREQUENCY OF LOW-VALUE ACTIVITY DISPLACING LONG-TERM WORK?",
    "ALIGNMENT BETWEEN TODAY'S OUTPUT AND THE INTENDED CAREER PATH?",
    "IS THE NEXT DEVELOPMENT MILESTONE ASSIGNED A DEADLINE?",
  ],
  relationship: [
    "QUALITY OF MEANINGFUL PEER OR FAMILY CONVERSATIONS?",
    "MINUTES OF UNDISTRACTED SOCIAL CONNECTION COMPLETED?",
    "CONSISTENCY OF ACTIVE LISTENING DURING INTERACTIONS?",
    "EFFECTIVENESS OF RESOLVING CURRENT INTERPERSONAL FRICTION?",
    "WAS CONTACT INITIATED WITH A VALUED FRIEND OR FAMILY MEMBER?",
    "WAS SPECIFIC APPRECIATION COMMUNICATED TO ANOTHER PERSON?",
    "QUALITY OF ATTENTION DURING SHARED TIME?",
    "WERE PERSONAL AND PEER BOUNDARIES RESPECTED?",
    "CURRENT LEVEL OF UNRESOLVED SOCIAL TENSION?",
    "FOLLOW-THROUGH ON PROMISES MADE TO FRIENDS OR FAMILY?",
  ],
  money: [
    "WAS SPENDING KEPT WITHIN THE AVAILABLE ALLOWANCE OR STUDENT BUDGET?",
    "TOTAL UNEXPECTED OR NON-ESSENTIAL EXPENDITURE?",
    "MINUTES ALLOCATED TO REVIEWING PERSONAL FINANCES?",
    "WAS THE PLANNED SAVINGS AMOUNT RETAINED?",
    "NUMBER OF DISCRETIONARY PURCHASES MADE?",
    "WERE ALL DIGITAL WALLET AND BANK TRANSACTIONS REVIEWED?",
    "MINUTES INVESTED IN PART-TIME WORK OR INCOME SKILL DEVELOPMENT?",
    "WERE ALL CURRENT PAYMENT OBLIGATIONS MET ON SCHEDULE?",
    "CURRENT STRESS ASSOCIATED WITH AVAILABLE FUNDS?",
    "CLARITY OF REMAINING FUNDS UNTIL THE NEXT INCOME EVENT?",
  ],
};

const adultQuestions: Record<string, string[]> = {
  health: [
    "TOTAL RESTORATIVE SLEEP DURATION DURING THE PREVIOUS NIGHT?",
    "SELF-ASSESSED HYDRATION ADEQUACY RELATIVE TO ACTIVITY LOAD?",
    "WAS CARDIOVASCULAR INTENSITY ABOVE BASELINE COMPLETED?",
    "TOTAL STEP COUNT RECORDED ACROSS WORK AND PERSONAL HOURS?",
    "NUMBER OF NUTRITIONALLY COMPLETE MEALS CONSUMED?",
    "CURRENT OCCUPATIONAL AND PERSONAL STRESS LOAD?",
    "WAS DEDICATED MOBILITY OR JOINT-MAINTENANCE WORK COMPLETED?",
    "MINUTES OF DIRECT OUTDOOR LIGHT EXPOSURE?",
    "CURRENT PHYSICAL ENERGY AVAILABILITY AFTER PRIMARY OBLIGATIONS?",
    "WAS THE ESTABLISHED SLEEP-WAKE SCHEDULE MAINTAINED?",
  ],
  studies: [
    "HOURS OF DELIBERATE PROFESSIONAL OR ACADEMIC LEARNING COMPLETED?",
    "NUMBER OF NEW CONCEPTS RETAINED WITHOUT EXTERNAL REFERENCE?",
    "FREQUENCY OF WORKFLOW OR DEVICE INTERRUPTIONS?",
    "UNAIDED RECALL ACCURACY FOR THE MATERIAL PROCESSED?",
    "NUMBER OF APPLIED EXERCISES OR CASE PROBLEMS COMPLETED?",
    "WAS THE SCHEDULED KNOWLEDGE-RETENTION REVIEW COMPLETED?",
    "WERE COGNITIVE RECOVERY INTERVALS OBSERVED AS PLANNED?",
    "PAGES PROCESSED WITH ACTIVE SYNTHESIS OR ANNOTATION?",
    "COGNITIVE ENERGY DURING THE FINAL LEARNING BLOCK?",
    "IS THE NEXT LEARNING SESSION DEFINED BY OUTCOME AND START TIME?",
  ],
  future: [
    "MINUTES INVESTED IN THE CURRENT FIVE-YEAR TRAJECTORY?",
    "MINUTES ALLOCATED TO HIGH-LEVERAGE SKILL ACQUISITION?",
    "WAS A PROFESSIONAL NETWORKING ACTION COMPLETED?",
    "MEASURABLE PROGRESS TOWARD THE CURRENT CAREER MILESTONE?",
    "MINUTES SPENT BUILDING A PORTFOLIO, PRODUCT, OR CAREER ASSET?",
    "WERE RELEVANT MARKET OR PROFESSIONAL OPPORTUNITIES REVIEWED?",
    "NUMBER OF PENDING STRATEGIC DECISIONS RESOLVED?",
    "FREQUENCY OF LOW-VALUE WORK DISPLACING LONG-TERM PRIORITIES?",
    "ALIGNMENT BETWEEN TODAY'S OUTPUT AND THE INTENDED LIFE DIRECTION?",
    "IS THE NEXT STRATEGIC MILESTONE ASSIGNED A DEADLINE?",
  ],
  relationship: [
    "QUALITY OF MEANINGFUL PARTNER, FAMILY, OR PEER CONVERSATIONS?",
    "MINUTES OF UNDISTRACTED SOCIAL CONNECTION COMPLETED?",
    "CONSISTENCY OF ACTIVE LISTENING DURING MATERIAL CONVERSATIONS?",
    "EFFECTIVENESS OF RESOLVING CURRENT INTERPERSONAL CONFLICT?",
    "WAS CONTACT INITIATED WITH A VALUED PERSONAL CONNECTION?",
    "WAS SPECIFIC APPRECIATION COMMUNICATED TO A PARTNER OR PEER?",
    "QUALITY OF ATTENTION DURING SHARED TIME?",
    "WERE PERSONAL, PARTNER, AND PROFESSIONAL BOUNDARIES RESPECTED?",
    "CURRENT LEVEL OF UNRESOLVED INTERPERSONAL TENSION?",
    "FOLLOW-THROUGH ON RELATIONAL AND FAMILY COMMITMENTS?",
  ],
  money: [
    "DID SPENDING ADHERE TO THE PRIMARY INCOME BUDGET?",
    "TOTAL UNEXPECTED UTILITY, LIVING, OR DISCRETIONARY EXPENDITURE?",
    "MINUTES ALLOCATED TO CASH-FLOW AND FINANCIAL PLANNING?",
    "WAS CAPITAL ALLOCATED TO SAVINGS OR THE INVESTMENT PORTFOLIO?",
    "NUMBER OF UNPLANNED DISCRETIONARY PURCHASES?",
    "WERE ALL BANK, CREDIT, AND INVESTMENT TRANSACTIONS REVIEWED?",
    "MINUTES INVESTED IN INCOME EXPANSION OR ASSET DEVELOPMENT?",
    "WERE DEBT AND RECURRING PAYMENT OBLIGATIONS MET AS PLANNED?",
    "CURRENT FINANCIAL STRESS LOAD?",
    "CLARITY OF NET CASH FLOW AND AVAILABLE LIQUID CAPITAL?",
  ],
};

export function getQuestions(pillar: string, age: number): string[] {
  const normalizedPillar = pillar.toLowerCase();

  if (age < 22) {
    return [...(studentQuestions[normalizedPillar] ?? [])];
  } else {
    return [...(adultQuestions[normalizedPillar] ?? [])];
  }
}

export function calculateAgeFromDob(dobValue: string): number | null {
  const parts = dobValue.split("-").map(Number);
  if (parts.length !== 3 || parts.some((part) => !Number.isInteger(part))) {
    return null;
  }

  const [year, month, day] = parts;
  const birthDate = new Date(year, month - 1, day);
  const today = new Date();

  if (
    birthDate.getFullYear() !== year ||
    birthDate.getMonth() !== month - 1 ||
    birthDate.getDate() !== day ||
    birthDate > today
  ) {
    return null;
  }

  let age = today.getFullYear() - year;
  const birthdayPassed =
    today.getMonth() > month - 1 ||
    (today.getMonth() === month - 1 && today.getDate() >= day);

  if (!birthdayPassed) age -= 1;
  return age >= 0 && age <= 120 ? age : null;
}
